services:
  cron-job-backend:
    container_name: cron-job-${NODE_ENV}-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    command: sh -c "yarn start"
    networks:
      cron-job:

#  mongo:
#    container_name: cron-job-${NODE_ENV}-mongo
#    image: mongo:6.0
#    restart: always
#    environment:
#      MONGO_INITDB_DATABASE: ${FACEIT_DB_DATABASE}
#      MONGO_INITDB_ROOT_USERNAME: ${FACEIT_DB_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${FACEIT_DB_PASSWORD}
#    ports:
#      - ${DATABASE_PORT}:27017
#    volumes:
#      - db_data:/data/db
#    networks:
#      cron-job:

volumes:
  db_data:
    name: db_data

networks:
  cron-job:
    name: cron-job
